name: secret demo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: secret demo
        run: echo "secret:" + ${{ secrets.KEY }}
